### ISSUE TITLE
Question about filtering spec

### ISSUE THREAD

**Issue by andrewmartin** [Superformula/frontend-test#2]
> The filter navigation needs to be able to perform real time filtering on both client side data, as well as server side queries.

Hi @wprater, mind offering a little more insight as to the details here? Are we looking for an isomorphic build?

**Comment by aaron-sf** [comment]
Hi @andrewmartin – in the context of filtering, `client side` means filtering local stores to display matched items, whereas `server side` queries would use the yelp's API parameters to fetch data

**Comment by drew-sf** [comment]
Thanks!
