### ISSUE TITLE
Question around yelp reviews getting truncated in their API.

### ISSUE THREAD

**Issue by ZackMFleischman** [Superformula/frontend-test#25]
From the [docs](https://www.yelp.com/developers/faq) 
>  How can I get access to full review text?
The Yelp API does not return full review text. Three review excerpts of 160 characters are provided by default.

The yelp API appears to only return excerpts of reviews of the first 160 characters, which isn't particularly great from a UX perspective.

The review DOES have a URL of the full yelp page of the review associated with it, and I could probably use the review excerpt in conjunction with a page scraper like [jssoup](https://www.npmjs.com/package/jssoup) to scrape the full review. That feels like a fair amount of work though, and although I'm happy to do it, I wanted to get your opinion on whether or not it would be worth my time to explore that, or if the excerpts are sufficient. 

Thanks,
Zack

**Comment by julian-sf** [comment]
Good question! You can move forward assuming the excerpts are sufficient.  No need to scrape information from elsewhere.
