### ISSUE TITLE
Question about CORS

### ISSUE THREAD

**Issue by andrewmartin** [Superformula/frontend-test#3]
Hi there, I'm hitting a CORS error when attempting to hit the Yelp endpoints. Any chance we can enable CORS on the Yelp API and / or provide an endpoint that is CORS enabled? Or is it a requirement to add an express app to proxy the requests over?

Much appreciated––

**Comment by wprater** [comment]
We can use a simple node proxy for this.  Thanks for the note, we'll add an update to the README.

cc @aaron-sf
